services:
  api:
    build: .
    command: ["python", "src/autostems.py", "serve", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./inputs:/app/inputs
      - ./outputs:/app/outputs
      - ./reports:/app/reports
  web:
    build: .
    command: ["python", "src/autostems.py", "webui"]
    ports:
      - "8501:8501"
    volumes:
      - ./inputs:/app/inputs
      - ./outputs:/app/outputs
      - ./reports:/app/reports
